In [12]:
# numpy vs python list 

import numpy as np 
import time 

# python list 

size = 100000
list1 = list(range(size))
list2  = list(range(size))

start = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()
print("python list addition time is:",end-start)


# numpy array 

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1+arr2 
# this is vectorized operation 

end = time.time()
print("numpy array addition time", end-start)


# numpy is significantly faster because it performs operations in c avoiding python in loops 





python list addition time is: 0.008420228958129883
numpy array addition time 0.002013683319091797


In [6]:
# creating numpy arrays 

# creating a 1d numpy array 
arr1 = np.array([1,2,3,4,5])
print(arr1)

# creating a 2d numpy array 

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


# checking type and shape 

print("type", type(arr1))
print("type",arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
type <class 'numpy.ndarray'>
type (2, 3)


In [7]:
# memory efficiency - numpy vs list 
# numpy array use significantly less memory compared to python list 

list_data = list(range(1000))
numpy_data  = np.array(list_data)

print("python list size:",sys.getsizeof(list_data)*len(list_data),"bytes")
print("numpy array size::",numpy_data.nbytes,"bytes")

python list size: 8056000 bytes
numpy array size:: 4000 bytes


In [11]:
# sauaring elements 

# python list (loop based)

list_squares = [x** 2 for x in list1]

# in numpy 

numpy_squares = arr1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'