In [1]:
# creating numpy array 

import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [12]:
# creating arrays from scratch 
import numpy as np
x = np.zeros((3,3))
print(x)


# 2*4 array of ones 
y = np.ones((2,4))
print(y)

# 2*2 array filled with 7 
z = np.full((2,2),7)
print(z)


# identity matrix 
a = np.eye(4) 
print(a)

# like range 
b = np.arange(1,10,2)
print(b)

# evenly spaced 
c = np.linspace(0,1,5)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


In [16]:
# checking array properties 

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("shape is",arr.shape)
print("size is: ", arr.size)
print("dimension is",arr.ndim)
print("data type",arr.dtype)

shape is (3, 3)
size is:  9
dimension is 2
data type int32


In [18]:
# changing data type 
arr = np.array([1,2,3],dtype = np.float32)
print(arr.dtype)

# convert float to int 
arr_int = arr.astype(np.int32)
print(arr_int)

float32
[1 2 3]


In [22]:
# reshaping and flattening of an array 

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)


# change shape 
reshaped = arr.reshape((3,2))
print(reshaped)

# convert 2d to 1d 
flattened = arr.flatten()
print(flattened)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
