In [2]:
# indexing and slicing 

import numpy as np 

arr = np.array([10,20,30])
print(arr[0])
# from the last 
print(arr[-1])

10
30


In [5]:
# slicing -> extracting parts of an array 

arr = np.array([10,20,30,40,50])

# slice from index 1 to 3 
print(arr[1:4])
# first 3 element 
print(arr[:3])
# every second element 
print(arr[::2])



# important points 
# Jo changes aap sliced array me karoge, wo original array me bhi reflect honge
# Agar changes ka impact nahi chahiye, toh .copy() ka use karo.




[20 30 40]
[10 20 30]
[10 30 50]


In [7]:
# fancy indexing and boolean masking 


# fancy indexing 
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])


# boolean masking 
arr = np.array([10,20,30,40,50])
# condition : values greater than 25
mask = arr>25
print(arr[mask])


[10 30 50]
[30 40 50]
