In [1]:
# broadcasting in numpy 
# Chhoti size ka array → bada banake → operation perform hota hai.


# why loops are slow 
import numpy as np 

arr = np.array([1,2,3,4,5])
result = []

# using a loop to square each element(slow)
for num in arr:
    result.append(num**2)

print(result)




[1, 4, 9, 16, 25]


In [3]:
# vectorization -> fixing the loop problem 

# vectorization allows you to perform operation on entire arrays at once, 
# instead of iterating over elements one by one


arr = np.array([1,2,3,4,5])
# vectorized operation
result = arr ** 2
print(result)  


[ 1  4  9 16 25]


In [11]:
# broadcasting 
import numpy as np
array = np.array([1,2,3,4,5])
result = array+10
print(result)


# broadcasting with array of different shapes 

arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

# element wise addition 
result = arr1+arr2
print(result)


# broadcasting a 2d array and a 1d array
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([1,2,3])
result1 = arr3+arr4
print(result1)

[11 12 13 14 15]
[11 22 33]
[[2 4 6]
 [5 7 9]]


In [12]:
# applying broadcasting to real world scenarios 

# row -> sample
# column -> features 
data = np.array([[10, 20, 30],
                [15, 25, 35],
                [20, 30, 40],
                [25, 35, 45],
                [30, 40, 50]])

# calculating mean and standard deviation

mean = data.mean(axis=0)
std = data.std(axis=0)

# normalizing the data using broadcasting 

normalized_data = (data-mean)/std
print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
