In [1]:
# create a 3*3 matrix array filled with random 
# number and print its shape 


import numpy as np 

arr  = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)



(3, 3)


In [2]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.

import numpy as np 

array = np.array( [1.1, 2.2, 3.3])

arr_int = array.astype(np.int32)
print(arr_int)


[1 2 3]


In [4]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6] .


import numpy as np 
array = np.array([1,2,3,4,5,6])
index = [1,3,5]
print(array[index])

[2 4 6]


In [5]:
# reshaping of an 1d array into 3d 


import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9])
# reshaping
reshaping = arr.reshape(3,3)
print(reshaping)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
