In [2]:
# 1d array - 1 axis 

# axes in 2d array 

import numpy as np 
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# summing along axes 

# sum along rows
# operation move down the columns
print(np.sum(arr,axis=0))

# sum along columns 
# operation move across the rows 
print(np.sum(arr,axis=1))



[12 15 18]
[ 6 15 24]


In [5]:
# indexing in multidimensional array 
import numpy as np 
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# accesing an element 
print(arr[1,2])
# means first row ka second columns 


# slicing 

print(arr[0:2,1:3])

6
[[2 3]
 [5 6]]


In [7]:
# indexing in 3d ararys 

arr3d = np.array ([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

print(arr3d)
print(arr3d.shape)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [9]:
# selecting data along axes 

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) # Output: (2, 2, 3) 

print(arr3D[0,1,2])
print(arr3D[:,0,:])


(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]
